<?php

namespace IfRPGMaker\SystemeJeuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierRepository extends EntityRepository
{
}
