<?php

namespace IfRPGMaker\SystemeJeuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartieCorpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieCorpsRepository extends EntityRepository
{
}
