parameters:
#    dialogue.example.class: IfRPGMaker\DialogueBundle\Example

services:
#    dialogue.example:
#        class: %dialogue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
