<?php

namespace IfRPGMaker\HistoireBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\DriverManager;

/**
 * HistoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoireRepository extends EntityRepository
{
    public function getConnection()
    {
        return $this->_em->getConnection();
    }
    
    public function find($id)
    {
        $sql = "SELECT * FROM Histoire WHERE titre=".$id['titre']." AND auteur_id=".$id['auteur_id'];
        
        $query = $this->createQueryBuilder("i")
                ->where("i.titre = :titre")
                ->setParameter("titre", $id['titre'])
                ->andWhere("i.auteur_id = :auteur_id")
                ->setParameter("auteur_id", $id['auteur_id'])
                ->getQuery();
                
       $res = $query->getResult();
        if (empty($res))
            $res = NULL;
        else
            $res = $res[0];
        return array("sql" => $sql, "entity"=> $res);
    }
    
    public function findByTitre($titre)
    {
        $sql = "SELECT * FROM Histoire WHERE titre = " .$titre;
        
        $query = $this->createQueryBuilder("i")
                ->where("i.titre = :titre")
                ->setParameter("titre", $titre)
                ->getQuery();
        
        $res = $query->getResult();
        return array("sql" => $sql, "entities"=> $res);
    }
    
    public function findAll()
    {
        $sql = "SELECT * FROM Histoire";
        
        $query = $this->createQueryBuilder("i")->getQuery();
        $res = $query->getResult();
        
        return array("sql" => $sql, "entities" => $res);
    }
    
    public function insert($entity) {
        $sql = "INSERT INTO Histoire (contenu) VALUES ('".$entity->getContenu()."')";
        $conn = $this->getConnection();
        
        $conn->insert('Histoire', array('contenu' => $entity->getContenu()));
        
        return array('sql' => $sql, 'id' => $conn->lastInsertId());
    }
    
    public function delete($entity) {
        $sql = "DELETE FROM Histoire WHERE id=".$entity->getId();
        
        $conn = $this->getConnection();
        $conn->delete('Histoire', array('id' => $entity->getId()));
        
        return $sql;
    }
    
    public function update($entity) {
        $sql = "UPDATE Histoire SET contenu='".$entity->getContenu()."' WHERE id =".$entity->getId();
        
        $conn = $this->getConnection();
        $conn->update('Histoire', 
                array('contenu' => $entity->getContenu()), 
                array('id' => $entity->getId())
                );
        
        return $sql;
    }
}
