<?php

namespace IfRPGMaker\HistoireBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\DriverManager;

/**
 * ScenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenarioRepository extends EntityRepository
{
    public function getConnection()
    {
        return $this->_em->getConnection();
    }
    
    public function find($id)
    {
        $sql = "SELECT * FROM Scenario WHERE id = ".$id;
        
        $query = $this->createQueryBuilder("i")
                ->where("i.id = :id")
                ->setParameter("id", $id)
                ->getQuery();
                
       $res = $query->getResult();
        if (empty($res))
            $res = NULL;
        else
            $res = $res[0];
        return array("sql" => $sql, "entity"=> $res);
    }
    
    public function findByContenu($contenu)
    {
        $sql = "SELECT * FROM Scenario WHERE contenu = " .$contenu;
        
        $query = $this->createQueryBuilder("i")
                ->where("i.contenu = :contenu")
                ->setParameter("contenu", $contenu)
                ->getQuery();
        
        $res = $query->getResult();
        return array("sql" => $sql, "entities"=> $res);
    }
    
    public function findAll()
    {
        $sql = "SELECT * FROM Scenario";
        
        $query = $this->createQueryBuilder("i")->getQuery();
        $res = $query->getResult();
        
        return array("sql" => $sql, "entities" => $res);
    }
    
    public function insert($entity) {
        $sql = "INSERT INTO Scenario (contenu) VALUES ('".$entity->getContenu()."')";
        $conn = $this->getConnection();
        
        $conn->insert('Scenario', array('contenu' => $entity->getContenu()));
        
        return array('sql' => $sql, 'id' => $conn->lastInsertId());
    }
    
    public function delete($entity) {
        $sql = "DELETE FROM Scenario WHERE id=".$entity->getId();
        
        $conn = $this->getConnection();
        $conn->delete('Scenario', array('id' => $entity->getId()));
        
        return $sql;
    }
    
    public function update($entity) {
        $sql = "UPDATE Scenario SET contenu='".$entity->getContenu()."' WHERE id =".$entity->getId();
        
        $conn = $this->getConnection();
        $conn->update('Scenario', 
                array('contenu' => $entity->getContenu()), 
                array('id' => $entity->getId())
                );
        
        return $sql;
    }
}
