liste_choix:
    pattern: /index
    defaults: { _controller: "HistoireBundle:Choix:index" }
    
new_choix:
    pattern: /new
    defaults: { _controller: "HistoireBundle:Choix:new" }

edit_choix:
    pattern: /edit
    defaults: { _controller: "HistoireBundle:Choix:edit" }
    
delete_choix:
    pattern: /delete
    defaults: { _controller: "HistoireBundle:Choix:delete" }
    