description:
    pattern:  /
    defaults: { _controller: "HistoireBundle:Description:index" }

description_show:
    pattern:  /{id}/show
    defaults: { _controller: "HistoireBundle:Description:show" }

description_new:
    pattern:  /new
    defaults: { _controller: "HistoireBundle:Description:new" }

description_create:
    pattern:  /create
    defaults: { _controller: "HistoireBundle:Description:create" }
    requirements: { _method: post }

description_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HistoireBundle:Description:edit" }

description_update:
    pattern:  /{id}/update
    defaults: { _controller: "HistoireBundle:Description:update" }
    requirements: { _method: post }

description_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HistoireBundle:Description:delete" }
    requirements: { _method: post }
