liste_evenement:
    pattern: /index
    defaults: { _controller: "HistoireBundle:Evenement:index" }
    
new_evenement:
    pattern: /new
    defaults: { _controller: "HistoireBundle:Evenement:new" }

edit_evenement:
    pattern: /edit
    defaults: { _controller: "HistoireBundle:Evenement:edit" }
    
delete_evenement:
    pattern: /delete
    defaults: { _controller: "HistoireBundle:Evenement:delete" }
    