<?php

namespace IfRPGMaker\PersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipementPersoHistoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementPersoHistoireRepository extends EntityRepository
{
}
