<?php

namespace IfRPGMaker\PersonnageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaractPersoHistoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaractPersoHistoireRepository extends EntityRepository
{
}
