HistoireBundle_intro:
    resource: "@HistoireBundle/Resources/config/routing/intro.yml"
    prefix:   /intro

HistoireBundle_description:
    resource: "@HistoireBundle/Resources/config/routing/description.yml"
    prefix:   /description

HistoireBundle_evenement:
    resource: "@HistoireBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

HistoireBundle_choix:
    resource: "@HistoireBundle/Resources/config/routing/choix.yml"
    prefix:   /choix

HistoireBundle_scenario:
    resource: "@HistoireBundle/Resources/config/routing/scenario.yml"
    prefix:   /scenario

HistoireBundle_histoire:
    resource: "@HistoireBundle/Resources/config/routing/histoire.yml"
    prefix:   /histoire
