HistoireBundle_evenement:
        resource: "@HistoireBundle/Resources/config/routing/evenement.yml"
        prefix:   /event
        
HistoireBundle_choix:
        resource: "@HistoireBundle/Resources/config/routing/choix.yml"
        prefix:   /choix

HistoireBundle_description:
        resource: "@HistoireBundle/Resources/config/routing/description.yml"
        prefix:   /description

HistoireBundle_intro:
        resource: "@HistoireBundle/Resources/config/routing/intro.yml"
        prefix:   /intro


histoire_index:
    pattern:  /liste
    defaults: { _controller: HistoireBundle:Histoire:index }
