parameters:
#    histoire.example.class: IfRPGMaker\HistoireBundle\Example

services:
#    histoire.example:
#        class: %histoire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
