parameters:
    database_driver:   pdo_mysql
    database_host:     dbserver
    database_port:     ~
    database_name:     nendredi
    database_user:     nendredi
    database_password: totoSalut

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
