systeme_jeu:
    resource: "@SystemeJeuBundle/Resources/config/routing.yml"
    prefix:   /

personnage:
    resource: "@PersonnageBundle/Resources/config/routing.yml"
    prefix:   /

dialogues:
    resource: "@DialoguesBundle/Resources/config/routing.yml"
    prefix:   /

actions:
    resource: "@ActionsBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

histoire:
    resource: "@HistoireBundle/Resources/config/routing.yml"
    prefix:   /histoire

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
