
PersonnageBundle_equipementpersohistoire:
    resource: "@PersonnageBundle/Resources/config/routing/equipementpersohistoire.yml"
    prefix:   /equipementpersohistoire


personnage_personnage:
    resource: "@PersonnageBundle/Resources/config/routing/personnage.yml"
    prefix:   /personnage


PersonnageBundle_caractpersohistoire:
    resource: "@PersonnageBundle/Resources/config/routing/caractpersohistoire.yml"
    prefix:   /caractpersohistoire
