<?php

namespace IfRPGMaker\ActionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionsRepository extends EntityRepository
{
}
