<?php

namespace IfRPGMaker\ActionsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiKeyRepository extends EntityRepository
{
}
