systeme_jeu_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SystemeJeuBundle:Default:index }

SystemeJeuBundle_caracteristique:
    resource: "@SystemeJeuBundle/Resources/config/routing/caracteristique.yml"
    prefix:   /caracteristique

SystemeJeuBundle_classe:
    resource: "@SystemeJeuBundle/Resources/config/routing/classe.yml"
    prefix:   /classe


SystemeJeuBundle_metier:
    resource: "@SystemeJeuBundle/Resources/config/routing/metier.yml"
    prefix:   /metier

SystemeJeuBundle_objet:
    resource: "@SystemeJeuBundle/Resources/config/routing/objet.yml"
    prefix:   /objet

SystemeJeuBundle_partiecorps:
    resource: "@SystemeJeuBundle/Resources/config/routing/partiecorps.yml"
    prefix:   /partiecorps

SystemeJeuBundle_systemejeu:
    resource: "@SystemeJeuBundle/Resources/config/routing/systemejeu.yml"
    prefix:   /systemejeu

SystemeJeuBundle_taille:
    resource: "@SystemeJeuBundle/Resources/config/routing/taille.yml"
    prefix:   /taille

SystemeJeuBundle_typeobjet:
    resource: "@SystemeJeuBundle/Resources/config/routing/typeobjet.yml"
    prefix:   /typeobjet
    
SystemeJeuBundle_race:
    resource: "@SystemeJeuBundle/Resources/config/routing/race.yml"
    prefix:   /race

