parameters:
#    system_jeu.example.class: IfRPGMaker\SystemeJeuBundle\Example

services:
#    system_jeu.example:
#        class: %system_jeu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
