ActionsBundle_actikey:
    resource: "@ActionsBundle/Resources/config/routing/actikey.yml"
    prefix:   /actikey
    
ActionsBundle_actions:
    resource: "@ActionsBundle/Resources/config/routing/actions.yml"
    prefix:   /actions

ActionsBundle_keywords:
    resource: "@ActionsBundle/Resources/config/routing/keywords.yml"
    prefix:   /keywords

ActionsBundle_dictionnaire:
    resource: "@ActionsBundle/Resources/config/routing/dictionnaire.yml"
    prefix:   /dictionnaire
