fos_user_bundle:
    resource: "@UserBundle/Resources/config/routing/routing_fos.yml"
    prefix:   /

user_bundle_joueur:
    resource: "@UserBundle/Resources/config/routing/joueur.yml"
    prefix:   /joueur