<?php

namespace IfRPGMaker\DialoguesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DialoguesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DialoguesRepository extends EntityRepository
{
}
