<?php

namespace IfRPGMaker\DialogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DialogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DialogueRepository extends EntityRepository
{
}
