parameters:
#    dialogues.example.class: IfRPGMaker\DialoguesBundle\Example

services:
#    dialogues.example:
#        class: %dialogues.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
