<?php

namespace IfRPGMaker\ContraintesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementContrainteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementContrainteRepository extends EntityRepository
{
}
